language: node_js
node_js:
  - "11"
dist: trusty
sudo: required
notifications:
  slack: smarthikeinc:5No8nUlnuaXrlTL4vkAI32Kq
branches:
  only:
    - staging
before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli
  - npm install
  - ng lint
script:
  -  'if [ "$TRAVIS_EVENT_TYPE" = "push" ] ; then
        ng build --prod ;
      fi'
after_success:
  - 'if [ "$TRAVIS_EVENT_TYPE" = "push" ] ; then
      firebase deploy --token=${FIREBASE_API_TOKEN} ;
    fi'
