language: node_js
node_js:
  - "11"
dist: trusty
sudo: required
branches:
  only:
    - staging
before_script:
  - npm install -g @angular/cli
script:
  - npm install
  - ng lint
  - ng build --prod
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: ""
