language: node_js
node_js:
  - "11"
dist: trusty
sudo: required
branches:
  only:
    - staging
before_script:
  - npm install -g @angular/cli
  - npm install
  - ng lint
script:
  - ng build --prod
after_success:
  - firebase deploy --token=${FIREBASE_API_TOKEN}
