language: node_js
node_js:
  - "11"
dist: trusty
sudo: required
branches:
  only:
    - staging
before_script:
  - npm install -g @angular/cli
  - npm install
  - ng lint
script:
  -  if [ "$TRAVIS_EVENT_TYPE" = "push" ] ; ng build --prod ; fi
after_success:
  - if [ "$TRAVIS_EVENT_TYPE" = "push" ] ; firebase deploy --token=${FIREBASE_API_TOKEN} ; fi
